# Generated by Django 5.1.3 on 2026-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
